trustPolicy: no-downgrade
shellEmulator: true
cleanupUnusedCatalogs: true
catalogMode: prefer

packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@antfu/eslint-config': ^6.2.0
  '@quiteer/scripts': ^0.0.12
  '@quiteer/vite': ^0.0.6
  '@types/node': ^24.10.0
  '@unocss/eslint-plugin': ^66.5.10
  '@unocss/preset-icons': ^66.5.10
  '@unocss/preset-uno': ^66.5.10
  '@unocss/preset-wind3': ^66.5.10
  '@unocss/transformer-directives': ^66.5.10
  '@unocss/transformer-variant-group': ^66.5.10
  '@unocss/vite': ^66.5.10
  eslint: ^9.39.1
  lint-staged: ^16.2.7
  naive-ui: ^2.43.2
  pinia: ^3.0.4
  prettier: ^3.7.4
  simple-git-hooks: ^2.13.1
  turbo: ^2.6.2
  typescript: 5.9.3
  unocss: ^66.5.10
  vue: ^3.5.25
  vue-router: ^4.6.3
