packages:
  - .
  - apps/*
  - docs/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@iconify/vue': ^5.0.0
  '@micro-zoe/micro-app': 1.0.0-rc.28
  '@quiteer/naive-extra': ^0.0.2
  '@quiteer/unocss': ^0.0.7
  '@quiteer/vite': ^0.1.12
  "@quiteer/scripts": ^0.1.6
  '@types/node': ^24.10.9
  '@unocss/eslint-plugin': ^66.6.0
  '@vueuse/core': 14.1.0
  eslint: ^9.39.2
  lint-staged: ^16.2.7
  naive-ui: ^2.43.2
  pinia: ^3.0.4
  prettier: ^3.8.1
  simple-git-hooks: ^2.13.1
  turbo: ^2.8.1
  typescript: 5.9.3
  unplugin-vue-router: ^0.19.2
  vue: ^3.5.27
  vue-router: ^4.6.4

catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
